### PR TITLE
Get networks

### PR DESCRIPTION
**Pull request by Mercurii7**
#10

### CODE REVIEW

**Review by mfbz — DISMISSED** [review]
Top 👏

**Comment by mfbz** [comment]
Hyyy @Mercurii7 can you please update the branch so we merge this? 🚀

**Comment by Mercurii7** [comment]
Hey @mfbz, I've updated the branch based on the latest NWA commit

**Comment by Mercurii7** [comment]
I've updated GetNetworksInvocationResult to match [NEO dAPI](https://github.com/neo-ngd/neo-dapi-monorepo/tree/master/packages/neo-dapi#getnetworks) and attempted to add a WalletConnect implementation for it.

**Comment by mfbz** [comment]
GG WP!

**Pull request merged**
